// Generates reports/<slug>.html for each data/<slug>.json, by taking
// index.html as a template and inlining that lead's data in place of
// js/report-data.js. Run automatically by Vercel (see vercel.json) —
// no dependencies, plain Node.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'data');
const OUT_DIR = path.join(ROOT, 'reports');
const TEMPLATE_PATH = path.join(ROOT, 'index.html');

function escapeForInlineScript(json) {
  // Prevent a value containing "</script>" from closing the tag early.
  return json.replace(/</g, '\\u003c');
}

function buildOne(template, slug, data) {
  const dataScript =
    '<script>window.reportData = ' +
    escapeForInlineScript(JSON.stringify(data, null, 2)) +
    ';</script>';

  let html = template;
  html = html.replace(
    '<link rel="stylesheet" href="css/style.css">',
    '<link rel="stylesheet" href="../css/style.css">'
  );
  html = html.replace(
    '<script src="js/report-data.js"></script>',
    dataScript
  );
  html = html.replace(
    '<script src="js/report.js"></script>',
    '<script src="../js/report.js"></script>'
  );
  if (data.businessName) {
    html = html.replace(
      '<title>Website Health Report</title>',
      '<title>' + data.businessName + ' — Website Health Report</title>'
    );
  }
  html =
    '<!-- Auto-generated by scripts/build-reports.js from data/' +
    slug +
    '.json. Do not edit directly. -->\n' +
    html;
  return html;
}

function main() {
  if (!fs.existsSync(DATA_DIR)) {
    console.log('No data/ directory found, nothing to build.');
    return;
  }
  const template = fs.readFileSync(TEMPLATE_PATH, 'utf8');
  const files = fs.readdirSync(DATA_DIR).filter((f) => f.endsWith('.json'));

  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });

  for (const file of files) {
    const slug = file.replace(/\.json$/, '');
    const data = JSON.parse(fs.readFileSync(path.join(DATA_DIR, file), 'utf8'));
    const html = buildOne(template, slug, data);
    fs.writeFileSync(path.join(OUT_DIR, slug + '.html'), html);
    console.log('Built reports/' + slug + '.html');
  }
}

main();
